---
- name: Configurations to "remote" host
  hosts: remote
  remote_user: krzysiekok # Remote user
  become: yes
  roles:
    - setup

- name: Copying "docker" application folder on remote server
  hosts: remote
  remote_user: krzysiekok # Remote user
  become: yes
  roles:
    - app
